### ISSUE TITLE
モバイル端末閲覧時にマップ下部のCopyrightが表示されない

### ISSUE THREAD

**Issue by kyoya0819** [Code-for-Funabashi/map#59]
### 考えうる原因

マップの高さを100vhで指定しているが、モバイル端末のy軸方向の表示領域 ≠ 100vhである頃が原因であると考えられる。

### 解決策

- JSを用いて画面の高さを取得し、地図高さに反映させる関数を書く。
- useEffectでwindow.onload時とwindow.onresize時に発火させる。

もしくは

- CSSで`html, body, ~省略~ {height: 100%}`のように親要素の高さを継承する。

### 再現方法

- Android Chrome, FireFox
- iOS Safari, Chrome
- iPadOS Safari, Chrome

でアクセスする。（iOS, iPadOS15系だと再現しないかもです）

### 環境

- iPadOS 14.7.1 / iPad 6th / Safari
- iOS14.8 / iPhone11 / Safari

### その他

![F43DD506-4247-45BB-A386-07681A171380](https://user-images.githubusercontent.com/45027336/136729696-8e1fb408-0ab5-4376-864c-854de275a9f4.jpeg)

<img src="https://user-images.githubusercontent.com/45027336/136729959-1e33568e-a35a-47a2-b534-1dee4732dbae.jpeg" width="50%" />

**Comment by aca-ta** [comment]
ありがとうございます。気づきませんでした。

試せてないですが、以下で解決するという報告を見かけました。
```css
.leaflet-container {
    height: 100%;
}
```
https://stackoverflow.com/a/67604832
